/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMetaverseStaking } from "./IMetaverseStaking";

export { IMetaverseStaking__factory } from "./factories/IMetaverseStaking__factory";
